name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  dockerpublish:
    name: Docker build and push latest
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Generate image tags
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
          TAGS='["user/image:latest","user/image:'${GITHUB_REF/refs\/tags\//}'"]'
          else
          TAGS='["user/image:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS
      - name: Multi platform build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: natmorris/iocontrollergw:latest
  deploydocs:
    name: Deploy docs
    needs: dockerpublish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
