on:
  push:
    branches:
      - master

jobs:
  dockerpublish:
    name: Docker build and push latest
    runs-on: ubuntu-latest
    steps:
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}
          registry: hub.docker.com
          repository: natmorris/iocontrollergw
          tags: latest
  deploydocs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
