on:
  push:
    branches:
      - master

jobs:
  dockerpublish:
    name: Docker build and push latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: natmorris/iocontrollergw
          tags: latest
  deploydocs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
